var http = require('http');
var url = require('url');
var axios = require('axios');
var fs = require('fs');

function genOcorrencias(ocorrencias){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lista de Ocorrências</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-teal">
              <h1>Lista de Ocorrências</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Data</th>
                        <th>Animal</th>
                      </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.id}</td>
            <td>${ocorr.bite_date}</td>
            <td>${ocorr.SpeciesIDDesc}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
            </div>
            
            <footer class="w3-container w3-teal">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}

http.createServer((req, res) => {
    console.log(req.method + " " + req.url);

    if (req.url == '/'){
        fs.readFile('aux.html', (err, dados) => {
            res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
            res.write(dados);
            res.end();
        });
    } else if (req.url == '/w3.css') {
        fs.readFile('w3.css', (err, dados) => {
            res.writeHead(200, {'Content-Type': 'text/css; charset=utf-8'});
            res.write(dados);
            res.end();  
        });
    } else if (req.url == '/animaisJSON') {
        axios.get("http://localhost:3000/ocorrencias")
            .then((response) => {
                res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
                res.write(JSON.stringify(response.data));
                res.end();
            })
            .catch((erro) => {
                res.writeHead(500, {'Content-Type': 'text/html; charset=utf-8'});
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });
    } else if (req.url == '/animais') {
        axios.get("http://localhost:3000/ocorrencias?SpeciesIDDesc=DOG&GenderIDDesc=MALE&BreedIDDesc=YORKSHIRE%20TERRIER&WhereBittenIDDesc=BODY&color=BLACK&color=BROWN")
            .then((response) => {
                res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
                data = response.data;
                htmlString = genOcorrencias(data);
                res.write(htmlString);
                res.end();
            })
            .catch((erro) => {
                res.writeHead(500, {'Content-Type': 'text/html; charset=utf-8'});
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });
    }
    else {
        res.writeHead(400, {'Content-Type': 'text/html; charset=utf-8'});
        res.write("<p>Erro: Pedido não encontrado</p>");
        res.write("<pre>" + req.url + "</pre>");
    }

}).listen(2702);

console.log("Servidor à escuta na porta 2702..") 